version:  '3'
services:
  notebook:
      build: ./juplab
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/${NB_USER}/work
        - ${LOCAL_DATASETS}:/home/${NB_USER}/datasets
        - ${LOCAL_CONFIG}:/home/${NB_USER}/.jupyter
        - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
      ports:
        - ${PORT}:8888
        - "8787:8787"
        - 4444:4444
      environment:
        - CHOWN_HOME=yes
        - CHOWN_HOME_OPTS=-R
      env_file:
        - .env
        - local.env
      working_dir: /home/${NB_USER}
      user: root:root
      command: "start-notebook.sh \
        --ip 0.0.0.0 \
        --NotebookApp.password=${ACCESS_TOKEN} \
        --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"
